version: '3'

services:
  cednode0:
    container_name: cednode0
    image: "binance/cednode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-cechaind.log}
    volumes:
      - ./build:/cechaind:Z
    networks:
      localnet:
        ipv4_address: 172.20.0.2

  cednode1:
    container_name: cednode1
    image: "binance/cednode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-cechaind.log}
    volumes:
      - ./build:/cechaind:Z
    networks:
      localnet:
        ipv4_address: 172.20.0.3

  cednode2:
    container_name: cednode2
    image: "binance/cednode"
    environment:
      - ID=2
      - LOG=${LOG:-cechaind.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/cechaind:Z
    networks:
      localnet:
        ipv4_address: 172.20.0.4

  cednode3:
    container_name: cednode3
    image: "binance/cednode"
    environment:
      - ID=3
      - LOG=${LOG:-cechaind.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/cechaind:Z
    networks:
      localnet:
        ipv4_address: 172.20.0.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.20.0.0/16

